from tkinter import *
from tkinter import messagebox
import tempfile
import os


root=Tk()
root.title('PROGRAM KASIR_FIKRY AGUSTIYAN')
root.geometry('1280x720+0+0')
bg_color='light grey'
fg_color='black'
root.resizable(False, False)
Donat=IntVar()
Biskuit=IntVar()
Roti=IntVar()
Susu=IntVar()
Total=IntVar()
cb=StringVar()
cw=StringVar()
cr=StringVar()
cg=StringVar()
total_cost=StringVar()
def total():
    if Donat.get()==0 and Biskuit.get()==0 and Roti.get()==0 and Susu.get()==0:
        messagebox.showerror('Error','Please select number of quantity')
    else:
        b=Donat.get()
        w=Biskuit.get()
        r=Roti.get()
        g=Susu.get()
        t=float(b*3000+w*2000+r*1000+g*5000)
        Total.set(b + w + r + g)
        total_cost.set('Rp ' + str(round(t, 2)))
        cb.set('Rp '+str(round(b*3000,2)))
        cw.set('Rp '+str(round(w*2000,2)))
        cr.set('Rp '+str(round(r*4000,2)))
        cg.set('Rp '+str(round(g*5000,2)))
def struk():
    textarea.delete(1.0,END)
    textarea.insert(END,' Produk\t|  Jumlah Barang  |\tBiaya  \n')
    textarea.insert(END,f'\nDonat \t\t{Donat.get()}\t  {cb.get()}')
    textarea.insert(END,f'\n\nBiskuit \t\t{Biskuit.get()}\t  {cw.get()}')
    textarea.insert(END,f'\n\nRoti \t\t{Roti.get()}\t  {cr.get()}')
    textarea.insert(END,f'\n\nSusu \t\t{Susu.get()}\t  {cg.get()}')
    textarea.insert(END, f"\n\n================================")
    textarea.insert(END,f'\nTotal Harga\t\t{Total.get()}\t{total_cost.get()}')
    textarea.insert(END, f"\n================================")
def reset():
    textarea.delete(1.0,END)
    Donat.set(0)
    Biskuit.set(0)
    Roti.set(0)
    Susu.set(0)
    Total.set(0)
    cb.set('')
    cw.set('')
    cr.set('')
    cg.set('')
    total_cost.set('')
def keluar():
    if messagebox.askyesno('EXIT','Apakah Kamu Yakin Untuk keluar?'):
        root.destroy()
title=Label(root,pady=5,text="Toko Fiike",bd=12,bg=bg_color,fg=fg_color,font=('times new roman', 35 ,'bold'),relief=GROOVE,justify=CENTER)
title.pack(fill=X)
#===============Product Details=================
F1 = LabelFrame(root, text='', font=('times new roman', 18, 'bold'), fg=fg_color,bg=bg_color,bd=15,relief=RIDGE)
F1.place(x=5, y=90,width=800,height=500)
#=====================Heading==========================
itm=Label(F1, text='Barang', font=('times new roman',25, 'bold','underline'), fg=fg_color,bg=bg_color)
itm.grid(row=0,column=0,padx=20,pady=15)
n=Label(F1, text='Jumlah Barang', font=('times new roman',23, 'bold','underline'), fg=fg_color,bg=bg_color)
n.grid(row=0,column=1,padx=30,pady=15)
cost=Label(F1, text='Harga Barang', font=('times new roman',25, 'bold','underline'), fg=fg_color,bg=bg_color)
cost.grid(row=0,column=2,padx=30,pady=15)
donat=Label(F1, text='Donat Rp. 3.000', font=('times new roman',16, 'bold'), fg=fg_color,bg=bg_color)
donat.grid(row=1,column=0,padx=20,pady=15)
b_txt=Entry(F1,font='arial 15 bold',relief=SUNKEN,bd=7,textvariable=Donat,justify=CENTER)
b_txt.grid(row=1,column=1,padx=20,pady=15)
cb_txt=Entry(F1,font='arial 15 bold',relief=SUNKEN,bd=7,textvariable=cb,justify=CENTER)
cb_txt.grid(row=1,column=2,padx=20,pady=15)
biskuit=Label(F1, text='Biskuit Rp. 2.000', font=('times new roman',16, 'bold'), fg=fg_color,bg=bg_color)
biskuit.grid(row=2,column=0,padx=20,pady=15)
w_txt=Entry(F1,font='arial 15 bold',relief=SUNKEN,bd=7,textvariable=Biskuit,justify=CENTER)
w_txt.grid(row=2,column=1,padx=20,pady=15)
cw_txt=Entry(F1,font='arial 15 bold',relief=SUNKEN,bd=7,textvariable=cw,justify=CENTER)
cw_txt.grid(row=2,column=2,padx=20,pady=15)
roti=Label(F1, text='Roti Rp. 4.000', font=('times new roman',16, 'bold'), fg=fg_color,bg=bg_color)
roti.grid(row=3,column=0,padx=20,pady=15)
r_txt=Entry(F1,font='arial 15 bold',relief=SUNKEN,bd=7,textvariable=Roti,justify=CENTER)
r_txt.grid(row=3,column=1,padx=20,pady=15)
cr_txt=Entry(F1,font='arial 15 bold',relief=SUNKEN,bd=7,textvariable=cr,justify=CENTER)
cr_txt.grid(row=3,column=2,padx=20,pady=15)
susu=Label(F1, text='Susu Rp. 5.000', font=('times new roman',16, 'bold'), fg=fg_color,bg=bg_color)
susu.grid(row=4,column=0,padx=20,pady=15)
g_txt=Entry(F1,font='arial 15 bold',relief=SUNKEN,bd=7,textvariable=Susu,justify=CENTER)
g_txt.grid(row=4,column=1,padx=20,pady=15)
cg_txt=Entry(F1,font='arial 15 bold',relief=SUNKEN,bd=7,textvariable=cg,justify=CENTER)
cg_txt.grid(row=4,column=2,padx=20,pady=15)
F4 = LabelFrame(root, text='', font=('times new roman', 18, 'bold'), fg=fg_color,bg=bg_color,bd=15,relief=RIDGE)
F4.place(x=5, y=480,width=800,height=200)
t=Label(F4, text='Total', font=('times new roman',20, 'bold'), fg=fg_color,bg=bg_color)
t.grid(row=5,column=0,padx=30,pady=15)
t_txt=Entry(F4,font='arial 15 bold',relief=SUNKEN,bd=7,textvariable=Total,justify=CENTER)
t_txt.grid(row=5,column=1,padx=40,pady=15)
totalcost_txt=Entry(F4,font='arial 15 bold',relief=SUNKEN,bd=7,textvariable=total_cost,justify=CENTER)
totalcost_txt.grid(row=5,column=2,padx=1,pady=15)

F2=Frame(root,relief=GROOVE,bd=10)
F2.place(x=820,y=90,width=430,height=500)
bill_title=Label(F2,text='Struk',font='arial 15 bold',bd=7,relief=GROOVE).pack(fill=X)
scrol_y=Scrollbar(F2,orient=VERTICAL)
scrol_y.pack(side=RIGHT,fill=Y)
textarea=Text(F2,font='arial 15',yscrollcommand=scrol_y.set)
textarea.pack(fill=BOTH)
scrol_y.config(command=textarea.yview)
F3 =Frame(root,bg=bg_color,bd=15,relief=RIDGE)
F3.place(x=5, y=590,width=1270,height=120)
btn_total = Button(F3, text='Total', font='arial 19 bold', padx=5, pady=5, bg=bg_color,fg=fg_color,width=10,command=total)
btn_total.grid(row=0,column=0,padx=20,pady=10)
btn_struk = Button(F3, text='Struk', font='arial 19 bold', padx=5, pady=5, bg=bg_color,fg=fg_color,width=10,command=struk)
btn_struk.grid(row=0,column=1,padx=10,pady=10)
btn_reset = Button(F3, text='Reset', font='arial 19 bold', padx=5, pady=5, bg=bg_color,fg=fg_color,width=10,command=reset)
btn_reset.grid(row=0,column=2,padx=10,pady=10)
btn_exit = Button(F3, text='Keluar', font='arial 19 bold', padx=5, pady=5, bg=bg_color,fg=fg_color,width=10,command=keluar)
btn_exit.grid(row=0,column=3,padx=10,pady=10)
footer = Label(F3, text='@Fikry Agustiyan_SMK Telkom Jakarta_2023', font="normal 12", bg='light grey', foreground='black')
footer.grid(row=0,column=4,padx=10,pady=10)
root.mainloop()